language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

sudo: required

services:
  - docker

before_script:
  - ln -s ../mvnw .mvn/mvn
  - export PATH=$PWD/.mvn:$PATH

script:
  - mvn clean install -V
